---
fail_fast: false
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character.
  - repo: local
    hooks:
      - id: system
        name: black
        entry: poetry run black .
        pass_filenames: false
        always_run: true
        language: system
      - id: system
        name: isort
        entry: poetry run isort --profile=black .
        pass_filenames: false
        always_run: true
        language: system
